In [1]:
import numpy as np

##### Basic Array creation 


In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
a=[1,2,3,4,'Hello']
a

[1, 2, 3, 4, 'Hello']

In [4]:
np.array(a)

array(['1', '2', '3', '4', 'Hello'], dtype='<U11')

In [5]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Array generation function

In [7]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [9]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [11]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Used for linear spacing
arr=np.linspace(1,10,4)
arr

array([ 1.,  4.,  7., 10.])

Random Generation Function

In [13]:
# Value lies between 0 to 1
arr=np.random.rand(5)
arr

array([0.34458831, 0.93160506, 0.59875747, 0.57044213, 0.48580981])

In [14]:
# Value lies between -3 to +3
arr=np.random.randn(10)
arr

array([-0.32776912,  0.14426841, -0.86993052, -1.01619775,  0.61128098,
        1.11260882, -0.20981939, -0.80419406, -0.91550072, -1.11445409])

In [15]:
arr=np.random.randint(5)
arr

0

In [16]:
arr=np.random.randint(5,20,3)
arr

array([ 8, 10, 15])

Array Attributes

In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int32')

Array Methods

In [21]:
arr.min(),arr.max(),arr.sum()

(1, 9, 45)

In [22]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [23]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [24]:
arr.mean(),arr.std(),arr.argmax(),arr.argmin()

(5.0, 2.581988897471611, 8, 0)

Reshaping And Resizing

In [25]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [26]:
arr=arr.reshape(6,5)

In [27]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])