Array Indexing

In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[5]

16

In [4]:
arr[1:5]

array([12, 13, 14, 15])

In [5]:
arr[:5]

array([11, 12, 13, 14, 15])

In [6]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3::2]

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [10]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0]

array([1, 2, 3, 4, 5])

In [12]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [14]:
arr[0][0]

1

In [15]:
arr[0,0]

1

In [17]:
arr[0,4]

5

In [18]:
arr[5,4]

30