Array Operations

In [1]:
import numpy as np

Arithmetic Operations

In [2]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [3]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [4]:
arr1=np.array([1,2,3,4,5,11])
arr2=np.array([6,7,8,9,10])

In [5]:
arr1+arr2 # Here the size of the array is different... Size must be same for arithmetic operations

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [6]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [7]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [8]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [9]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
arr2//arr2

array([1, 1, 1, 1, 1])

In [11]:
arr1**arr2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [12]:
l=[10,20,30,40]
arr=np.array(l)

In [13]:
l+10

TypeError: can only concatenate list (not "int") to list

In [14]:
arr+10

array([20, 30, 40, 50])

In [15]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [17]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep and Shallow copy

In [18]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
slice=arr[:5]

In [20]:
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [21]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
arr[4:6]*10

array([50, 60])

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
brr=arr
brr[0]=99

In [25]:
brr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
brr=arr.copy()
brr[0]=102

In [28]:
brr

array([102,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [29]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [30]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])

In [31]:
mat1

array([[1, 2],
       [3, 4]])

In [32]:
mat2

array([[5, 6],
       [7, 8]])

In [33]:
mat1@mat2

array([[19, 22],
       [43, 50]])

In [34]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [35]:
mat1.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation

Stacking Array

In [36]:
mat1

array([[1, 2],
       [3, 4]])

In [37]:
mat2

array([[5, 6],
       [7, 8]])

In [38]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [39]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [42]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [44]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [45]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]